application:
  config:
    description: Profile Default

server:
  port: 8082

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  messages:
    basename: i18n/messages
    fallback-to-system-locale: true
    use-code-as-default-message: true
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      host: localhost
      port: 27017
      database: accountdb
      auto-index-creation: false

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

service:
  client:
    uri: lb://client-service/api/v1/client
  credit:
    uri: lb://credit-service/api/v1/credit
