#PORT
server:
  port: 8080
  
##CONFIGURATION EUREKA CLIENT
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
        
#CONFIGURATION SPRING
spring:
  main:
    web-application-type: reactive  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clients
          uri: lb://client-service
          predicates:
            - Path=/api/v1/client/** 
          filters:
            - RewritePath=/api/ms1/(?<x>.*), /$\{x}
        - id: accounts
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account/**
          filters:
           - RewritePath=/api/ms1/(?<x>.*), /$\{x}    
        - id: credits
          uri: lb://credit-service
          predicates:
           - Path=/api/v1/credit/**
          filters:
           - RewritePath=/api/ms1/(?<x>.*), /$\{x}
        - id: transactions
          uri: lb://transaction-service
          predicates:
           - Path=/api/v1/transaction/**
          filters:
           - RewritePath=/api/ms1/(?<x>.*), /$\{x}          
        - id: reports
          uri: lb://report-service
          predicates:
           - Path=/api/v1/report/**
          filters:
           - RewritePath=/api/ms1/(?<x>.*), /$\{x} 
           
management:
  endpoints:
    web:
     exposure:
       include: "*"
     cors:
       allowed-origins: true 
                    
© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
