application:
  config:
    description: Profile Default

server:
  port: 8081

spring:  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: clientdb
  messages:
    basename: i18n/messages
    fallback-to-system-locale: true
    use-code-as-default-message: true
  jackson:
    default-property-inclusion: NON_NULL
    
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
