application:
  config:
    description: Profile Default

server:
  port: ${PORT:8081}

spring:
  data:
    mongodb:
      uri: ${MONGODB_CONNSTRING:mongodb://localhost:27017/clientdb}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:s3cret}
  messages:
    basename: i18n/messages
    fallback-to-system-locale: true
    use-code-as-default-message: true
  jackson:
    default-property-inclusion: NON_NULL

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: false
    env:
      enabled: false
