application:
  config:
    description: Profile Default

server:
  port: 0

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: creditdb
      auto-index-creation: false
  messages:
    basename: i18n/messages
    fallback-to-system-locale: true
    use-code-as-default-message: true
  jackson:
    default-property-inclusion: NON_NULL
    
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

service:
 client:
   uri: lb://client-service/api/v1/client
 account:
   uri: lb://account-service/api/v1/account
