application:
  config:
    description: Profile Default

server:
  port: ${PORT:8085}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  messages:
    basename: i18n/messages
    fallback-to-system-locale: true
    use-code-as-default-message: true
  jackson:
    default-property-inclusion: NON_NULL
    
eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}

service:
  client:
    uri: lb://client-service/api/v1/client
  account:
    uri: lb://account-service/api/v1/account
  credit:
    uri: lb://credit-service/api/v1/credit
  transaction:
    uri: lb://transaction-service/api/v1/transaction

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: false
    env:
      enabled: false