application:
  config:
    description: Profile Default

server:
  port: 8085

spring:
  messages:
    basename: i18n/messages
    fallback-to-system-locale: true
    use-code-as-default-message: true
  jackson:
    default-property-inclusion: NON_NULL
    
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

service:
  client:
    uri: lb://client-service/api/v1/client
  account:
    uri: lb://account-service/api/v1/account
  credit:
    uri: lb://credit-service/api/v1/credit
  transaction:
    uri: lb://transaction-service/api/v1/transaction