application:
  config:
    description: Profile Default

server:
  port: 8084

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: transactiondb
  messages:
    basename: i18n/messages
    fallback-to-system-locale: true
    use-code-as-default-message: true
  jackson:
    default-property-inclusion: NON_NULL
    
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
service:
  client:
    uri: http://localhost:8081/api/client
  account:
    uri: http://localhost:8082/api/v1/account
  credit:
    uri: http://localhost:8083/api/v1/credit
